### ISSUE TITLE
altum data after PPK correction 

### ISSUE THREAD

**Issue by ouhssam** [aewindle110/DroneWQ#2]
Dear Miss Windle
I am trying to run your code on my data for my altum camera mounted on a fixe wings UAV, but I got this error : 
process_raw_to_rrs(main_dir=project_path, rrs_dir_name='rrs_hedley', output_csv_path=project_path, lw_method='hedley_method', random_n=15,
...                    mask_pixels=False, ed_method='dls_ed', overwrite=False, clean_intermediates=False)
Processing a total of 342 captures or 68 image sets.
Converting raw images to radiance (raw -> Lt).
Loading ImageSet from: ./data//raw_water_imgs
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/ouhssam/imagedrone/WQ/DroneWQ/utils.py", line 699, in process_raw_to_rrs
    process_micasense_images(main_dir, warp_img_dir=os.path.join(main_dir,'align_img'), overwrite=overwrite, sky=False)
  File "/home/ouhssam/imagedrone/WQ/DroneWQ/utils.py", line 249, in process_micasense_images
    imgset = imageset.ImageSet.from_directory(img_dir)
  File "/home/ouhssam/imagedrone/WQ/DroneWQ/micasense/imageset.py", line 165, in from_directory
    images.append(image.Image(path, exiftool_obj=exift))
  File "/home/ouhssam/imagedrone/WQ/DroneWQ/micasense/image.py", line 77, in __init__
    self.utc_time = self.meta.utc_time()
  File "/home/ouhssam/imagedrone/WQ/DroneWQ/micasense/metadata.py", line 126, in utc_time
    utc_time = datetime.strptime(str_time, "%Y:%m:%d %H:%M:%S")
  File "/home/ouhssam/miniconda3/envs/dronewq/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/ouhssam/miniconda3/envs/dronewq/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '50 48 50 50 58 48 50 58 48 56 32 49 51 58 51 54 58 52 53 0' does not match format '%Y:%m:%d %H:%M:%S'

Please have you an idea how to fix it ?

**Comment by Ar-temis** [comment]
Seems like the exiftool scanned the date as an ASCII characters. 
`50 48 50 50 58 48 50 58 48 56 32 49 51 58 51 54 58 52 53 0`  maps to `"2022:02:08 13:36:45\0"`

We are using the micasense camera package underneath dronewq so it was probably due to camera mismatch.
